export { default as Hero } from './Hero';
export { default as About } from './About';
export { default as TechnicalSkills } from './TechnicalSkills';
export { default as Projects } from './Projects';
export { default as OpenSource } from './OpenSource';
export { default as Certifications } from './Certifications';
export { default as Testimonials } from './Testimonials';
export { default as Contact } from './Contact';
export { default as Footer } from './Footer';
